version: "3"

services:
  imagedownloader:
    image: imagedownloader
    restart: always
    container_name: imagedownloader
    #    network_mode: "host"
    ports:
      - "5005:5005"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./images:/images
      - ./logs:/logs
